In [1]:
#Importing the libaries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Reading the Dataset
dataset= pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
indep=dataset[['age','children','bmi','sex_male','smoker_yes']]
dep=dataset['charges']

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.2,random_state=0)

In [9]:
#from sklearn.preprocessing import StandardScaler
#sc=StandardScaler()
#x_train = sc.fit_transform(x_train)
#x_test=sc.transform(x_test)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf'],'C':[10],'gamma':['auto','scale']}
grid= GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
#fitting the model to grid search
grid.fit(x_train, y_train)

Fitting 5 folds for each of 2 candidates, totalling 10 fits

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf']},
             verbose=3)

In [28]:
#print best parameter
#print(grid.best _params)
re=grid.cv_results_
print("The R_score value for best parameter {} :".format(grid.best_params_))

The R_score value for best parameter {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'} :

In [29]:
table=pd.DataFrame.from_dict(re)

In [30]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.197747,0.039984,0.072057,0.010367,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.085654,-0.035809,-0.086097,-0.135719,-0.168261,-0.102308,0.045669,2
1,0.110652,0.005118,0.060530,0.001408,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.093661,-0.021248,-0.082944,-0.139818,-0.168440,-0.101222,0.050587,1

In [19]:
age=str(input("Age"))
bmi=float(input("BMI"))
children=float(input("Children"))
sex_male=int(input("Sex_Male 0 or 1:"))
smoker_yes=int(input("Smoker_yes 0 or 1:"))

Age 45
BMI 67.8
Children 2
Sex_Male 0 or 1: 0
Smoker_yes 0 or 1: 0

In [32]:
Future_Prediction=grid.predict([[age,bmi,children,sex_male,smoker_yes]])#
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[9051.26996211]

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(